
[env]
TERM = "xterm-256color"



[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.4

[window.padding]
x = 0
y = 0

[font]
size = 7.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[general]
# Alacritty Configuration

live_config_reload = true 


import = [
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]
